import{useState}from'react';import{Link}from'react-router';import{AnimatedList,AnimatedShinyText,BlurFade,BorderBeam,MagicCard,NumberTicker,Particles,TextAnimate}from'../../components/magicui';import{BrandMark}from'../../components/ui/BrandMark';import{PersonalBestChip}from'../../components/ui/PersonalBestChip';import styles from'./LandingPage.module.css';
const methods=[['01','Set the direction','Choose the action that helps—or the one you are ready to leave behind.'],['02','Make it visible','Show up today. One honest check-in is enough to move.'],['03','Learn the pattern','See the shape form across days, resets, and returns.']];
export function LandingPage(){const[complete,setComplete]=useState(false);return <div className={styles.page}>
  <nav className={styles.nav}><Link to="/" className={styles.brand}><BrandMark/><b>Habit Shaper</b></Link><div className={styles.navLinks}><a href="#method">Method</a><a href="#recovery">Recovery</a><Link to="/brand-kit">Brand Kit</Link></div><div className={styles.auth}><Link to="/login">Log in</Link><Link className="raisedPrimary" to="/register">Start now</Link></div></nav>
  <main>
    <section className={styles.hero}><div className={styles.heroCopy}><p className="eyebrow"><AnimatedShinyText>Small actions / visible progress</AnimatedShinyText></p><h1><TextAnimate>Build what helps.</TextAnimate><br/><TextAnimate delay={.35}>Break what holds you back.</TextAnimate></h1><BlurFade delay={.55}><p className={styles.intro}>Track daily actions, understand your streaks, and begin again when life gets in the way.</p><div className="cluster"><Link className="raisedPrimary" to="/register">Start with one habit</Link><a className="plainButton" href="#method">See the method ↓</a></div></BlurFade></div>
      <BlurFade delay={.25} className={styles.productStage}><MagicCard className={`${styles.preview} raisedCard`}><BorderBeam color="#E67A72"/><header><span>Today's step</span><b>{complete?'1 / 1 done':'0 / 1 done'}</b></header><div className={styles.previewHabit}><div><small>BUILD · DAILY</small><h3>Read for 20 minutes</h3><p><strong><NumberTicker value={complete?8:7}/></strong> day streak</p></div><button disabled={complete} className={complete?styles.done:'raisedPrimary'} onClick={()=>setComplete(true)}>{complete?'Completed ✓':'Complete today'}</button></div><div className={styles.week} aria-label="Weekly preview">{['M','T','W','T','F','S','S'].map((day,index)=><span key={`${day}${index}`} className={index<5||complete&&index===5?styles.filled:undefined}>{day}</span>)}</div>{complete&&<Particles burstKey="homepage-complete"/>}</MagicCard><PersonalBestChip value={complete?8:7} message={complete?'One more day shaped.':'One step from a new mark.'}/></BlurFade>
    </section>
    <section className={`${styles.momentum} reveal`}><div><strong>ONE ACTION.</strong><span>Then another.</span></div><div className={styles.blocks}><i/><i/><i/></div><div><strong>VISIBLE PROGRESS.</strong><span>No perfection required.</span></div></section>
    <section id="method" className={`${styles.method} pageWidth reveal`}><header><p className="eyebrow">The method</p><h2>Small steps.<br/>A shape you can see.</h2></header><AnimatedList className={styles.spine}>{methods.map(([number,title,copy])=><article key={number} tabIndex={0}><b>{number}</b><div><h3>{title}</h3><p>{copy}</p></div></article>)}</AnimatedList></section>
    <section id="recovery" className={`${styles.recovery} reveal`}><div className={styles.recoveryCopy}><p className="eyebrow">Recovery is progress</p><h2>A reset is data.<br/>Not a verdict.</h2><p>Your previous effort stays visible. Record the truth, learn the pattern, and shape the next choice.</p></div><div className={styles.recoveryStat}><img src="/brand/illustrations/recovery-progress.svg" alt="A progress path that pauses and continues"/><div><strong>46</strong><span>total steps still count</span></div></div></section>
    <section className={styles.final}><BrandMark size={68}/><p className="eyebrow">Start where you are</p><h2>Your next step<br/>can be small.</h2><Link className="raisedPrimary" to="/register">Shape your first habit</Link></section>
  </main><footer className={styles.footer}><div className={styles.brand}><BrandMark/><b>Habit Shaper</b></div><p>Small actions. Visible progress.</p><Link to="/brand-kit">Explore the brand kit</Link></footer>
  </div>}
