import { Plus, Search, X } from 'lucide-react';
import { useEffect, useMemo, useState, type KeyboardEvent, type ReactNode } from 'react';
import type { Goal, Habit, HabitType } from '../../types/domain';
import styles from './RelationComposer.module.css';

export type DraftGoal = { key: string; title: string; targetDays: number; deadline: string };
export type DraftHabit = { key: string; name: string; type: HabitType };
const normalized = (value: string) => value.trim().toLocaleLowerCase();

type Common = { pending?: boolean; error?: string; onError: (message: string) => void };

export function GoalRelationComposer({ goals, selectedIds, drafts, onSelectedIds, onDrafts, pending, error, onError }: Common & { goals: Goal[]; selectedIds: string[]; drafts: DraftGoal[]; onSelectedIds: (ids: string[]) => void; onDrafts: (drafts: DraftGoal[]) => void }) {
  const [search, setSearch] = useState(''); const [title, setTitle] = useState(''); const [targetDays, setTargetDays] = useState(7); const [deadline, setDeadline] = useState('');
  const [order, setOrder] = useState<string[]>([]);
  useEffect(() => { setOrder(current => [...current, ...selectedIds.map(id => `e:${id}`), ...drafts.map(draft => `d:${draft.key}`)].filter((value, index, values) => values.indexOf(value) === index)); }, [selectedIds, drafts]);
  const available = useMemo(() => goals.filter(goal => goal.status === 'ACTIVE' && !selectedIds.includes(goal.id) && goal.title.toLocaleLowerCase().includes(normalized(search))), [goals, search, selectedIds]);
  const addDraft = () => { const name = normalized(title); if (!name || targetDays < 1) return; if (drafts.some(draft => normalized(draft.title) === name) || goals.some(goal => selectedIds.includes(goal.id) && normalized(goal.title) === name)) { onError('Already added.'); return; } const key = crypto.randomUUID(); onError(''); setOrder(current => [...current.filter(value => value !== `d:${key}`), `d:${key}`]); onDrafts([...drafts, { key, title: title.trim(), targetDays, deadline }]); setTitle(''); setTargetDays(7); setDeadline(''); };
  const rows = [...selectedIds.map(id => ({ key: `e:${id}`, title: goals.find(goal => goal.id === id)?.title ?? 'Goal', kind: 'Existing' as const, remove: () => onSelectedIds(selectedIds.filter(value => value !== id)) })), ...drafts.map(draft => ({ key: `d:${draft.key}`, title: draft.title, kind: 'New' as const, remove: () => onDrafts(drafts.filter(value => value.key !== draft.key)) }))].sort((left, right) => order.indexOf(left.key) - order.indexOf(right.key));
  return <RelationShell label="Connected goals" itemLabel="goals" pending={pending} search={search} onSearch={setSearch} results={available.map(goal => ({ id: goal.id, title: goal.title, meta: `${goal.progress.currentDays}/${goal.targetDays} days` }))} onPick={id => { setOrder(current => [...current.filter(value => value !== `e:${id}`), `e:${id}`]); onSelectedIds([...selectedIds, id]); setSearch(''); onError(''); }} empty={search ? 'No matching active goals.' : 'No active goals available.'}>
    <Preview rows={rows} pending={pending} />
    <div className={styles.draft}><header><span>Or create a new goal</span><small>It will be created when you save.</small></header><label className={styles.field}><span>Goal title</span><input aria-label="New goal title" value={title} disabled={pending} onChange={event => setTitle(event.target.value)} onKeyDown={event => { if (event.key === 'Enter') { event.preventDefault(); addDraft(); } }} placeholder="30 focused mornings" /></label><div className={styles.fieldRow}><label className={styles.field}><span>Target days</span><input aria-label="Target days" type="number" min="1" value={targetDays} disabled={pending} onChange={event => setTargetDays(Number(event.target.value))} /></label><label className={styles.field}><span>Deadline <small>Optional</small></span><input aria-label="Goal deadline" type="date" value={deadline} disabled={pending} onChange={event => setDeadline(event.target.value)} /></label></div><button type="button" className="raisedSecondary" disabled={pending || !title.trim() || targetDays < 1} onClick={addDraft}><Plus /> Add goal</button></div>
    {error && <span className="fieldError" role="alert">{error}</span>}
  </RelationShell>;
}

export function HabitRelationComposer({ habits, selectedIds, drafts, onSelectedIds, onDrafts, pending, error, onError }: Common & { habits: Habit[]; selectedIds: string[]; drafts: DraftHabit[]; onSelectedIds: (ids: string[]) => void; onDrafts: (drafts: DraftHabit[]) => void }) {
  const [search, setSearch] = useState(''); const [name, setName] = useState(''); const [type, setType] = useState<HabitType>('BUILD');
  const [order, setOrder] = useState<string[]>([]);
  useEffect(() => { setOrder(current => [...current, ...selectedIds.map(id => `e:${id}`), ...drafts.map(draft => `d:${draft.key}`)].filter((value, index, values) => values.indexOf(value) === index)); }, [selectedIds, drafts]);
  const available = useMemo(() => habits.filter(habit => !selectedIds.includes(habit.id) && habit.name.toLocaleLowerCase().includes(normalized(search))), [habits, search, selectedIds]);
  const addDraft = () => { const value = normalized(name); if (!value) return; if (drafts.some(draft => normalized(draft.name) === value) || habits.some(habit => selectedIds.includes(habit.id) && normalized(habit.name) === value)) { onError('Already added.'); return; } const key = crypto.randomUUID(); onError(''); setOrder(current => [...current.filter(item => item !== `d:${key}`), `d:${key}`]); onDrafts([...drafts, { key, name: name.trim(), type }]); setName(''); setType('BUILD'); };
  const rows = [...selectedIds.map(id => ({ key: `e:${id}`, title: habits.find(habit => habit.id === id)?.name ?? 'Habit', kind: 'Existing' as const, remove: () => onSelectedIds(selectedIds.filter(value => value !== id)) })), ...drafts.map(draft => ({ key: `d:${draft.key}`, title: draft.name, kind: 'New' as const, remove: () => onDrafts(drafts.filter(value => value.key !== draft.key)) }))].sort((left, right) => order.indexOf(left.key) - order.indexOf(right.key));
  return <RelationShell label="Connected habits" itemLabel="habits" pending={pending} search={search} onSearch={setSearch} results={available.map(habit => ({ id: habit.id, title: habit.name, meta: habit.type === 'BUILD' ? 'Build · daily' : 'Break · daily' }))} onPick={id => { setOrder(current => [...current.filter(value => value !== `e:${id}`), `e:${id}`]); onSelectedIds([...selectedIds, id]); setSearch(''); onError(''); }} empty={search ? 'No matching habits.' : 'No habits available.'}>
    <Preview rows={rows} pending={pending} />
    <div className={styles.draft}><header><span>Or create a new habit</span><small>It will be created when you save.</small></header><label className={styles.field}><span>Habit name</span><input aria-label="New habit name" value={name} disabled={pending} onChange={event => setName(event.target.value)} onKeyDown={event => { if (event.key === 'Enter') { event.preventDefault(); addDraft(); } }} placeholder="Read for ten minutes" /></label><div className={styles.types}>{(['BUILD', 'BREAK'] as HabitType[]).map(value => <button type="button" key={value} disabled={pending} aria-pressed={type === value} onClick={() => setType(value)}><img src={`/brand/icons/${value.toLowerCase()}.svg`} alt="" /><span><strong>{value === 'BUILD' ? 'Build' : 'Break'}</strong><small>{value === 'BUILD' ? 'Repeat a helpful action.' : 'Move away from an action.'}</small></span></button>)}</div><button type="button" className="raisedSecondary" disabled={pending || !name.trim()} onClick={addDraft}><Plus /> Add habit</button></div>
    {error && <span className="fieldError" role="alert">{error}</span>}
  </RelationShell>;
}

function RelationShell({ label, itemLabel, pending, search, onSearch, results, onPick, empty, children }: { label: string; itemLabel: string; pending?: boolean; search: string; onSearch: (value: string) => void; results: { id: string; title: string; meta: string }[]; onPick: (id: string) => void; empty: string; children: ReactNode }) {
  const onKey = (event: KeyboardEvent<HTMLInputElement>) => { if (event.key === 'Enter' && results[0]) { event.preventDefault(); onPick(results[0].id); } };
  return <fieldset className={styles.composer} disabled={pending}><legend>{label}</legend><div className={styles.existing}><label><span className="fieldLabel">Add existing {itemLabel}</span><span className={styles.search}><Search /><input aria-label={`Search ${label.toLowerCase()}`} value={search} onChange={event => onSearch(event.target.value)} onKeyDown={onKey} placeholder={`Search ${itemLabel}…`} /></span></label><div className={styles.results} role="listbox" aria-label={`Available ${itemLabel}`}>{results.map(result => <button type="button" role="option" aria-selected="false" key={result.id} onClick={() => onPick(result.id)}><span><strong>{result.title}</strong><small>{result.meta}</small></span><i><Plus /></i></button>)}{!results.length && <p>{empty}</p>}</div></div>{children}</fieldset>;
}

function Preview({ rows, pending }: { rows: { key: string; title: string; kind: 'Existing' | 'New'; remove: () => void }[]; pending?: boolean }) {
  return <section className={styles.previewSection}><span className="fieldLabel">Selected</span><div className={styles.preview}>{rows.map(row => <div key={row.key}><span><strong>{row.title}</strong><small className={row.kind === 'New' ? styles.newBadge : undefined}>{row.kind}</small></span><button type="button" aria-label={`Remove ${row.title}`} disabled={pending} onClick={row.remove}><X /></button></div>)}{!rows.length && <p>Nothing selected yet.</p>}</div></section>;
}
