ALTER TABLE `User` ADD COLUMN `username` VARCHAR(191) NULL;

UPDATE `User`
SET `username` = SUBSTRING_INDEX(`email`, '@', 1)
WHERE `username` IS NULL;

ALTER TABLE `User` MODIFY COLUMN `username` VARCHAR(191) NOT NULL;
