import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useNavigate, useParams } from 'react-router';
import { LinearProgress } from '../../components/ui/Progress';
import { dashboardKey } from '../dashboard/DashboardPage';
import { goalsApi } from './goals.api';
import styles from './GoalDetailPage.module.css';
export function GoalDetailPage() {
  const { goalId = '' } = useParams(); const navigate = useNavigate(); const cache = useQueryClient(); const [confirm, setConfirm] = useState<'cancel'|'delete'|null>(null);
  const goals = useQuery({ queryKey: ['goals'], queryFn: goalsApi.list }); const goal = goals.data?.goals.find(item => item.id === goalId);
  const refresh = () => Promise.all([cache.invalidateQueries({ queryKey: ['goals'] }), cache.invalidateQueries({ queryKey: dashboardKey })]);
  const cancel = useMutation({ mutationFn: () => goalsApi.cancel(goalId), onSuccess: async () => { setConfirm(null); await refresh(); } });
  const remove = useMutation({ mutationFn: () => goalsApi.delete(goalId), onSuccess: async () => { await refresh(); navigate('/app/goals', { replace: true }); } });
  if (goals.isLoading) return <div className="stack"><div className="skeleton" /><div className="skeleton" /></div>;
  if (!goal) return <section className="panel"><h2>Goal not found.</h2><Link className="raisedSecondary" to="/app/goals">Back to goals</Link></section>;
  const created = new Date(goal.createdAt).toLocaleDateString('en', { dateStyle: 'medium' });
  return <><header className={styles.header}><div><div className="cluster"><span className={`${styles.status} ${styles[goal.status.toLowerCase()]}`}>{goal.status}</span><span className="muted">Created {created}</span></div><h1>{goal.title}</h1><p>A progress day needs every connected habit below.</p></div><Link className="raisedSecondary" to={`/app/goals/${goalId}/edit`}>Edit goal</Link></header>{goal.status === 'COMPLETED' && <section className={styles.completed}><img src="/brand/motion/milestone-day-7.svg" alt="" /><div><p className="eyebrow">Goal shaped</p><h2>{goal.targetDays} days. Done.</h2></div></section>}<section className={styles.hero}><div><p className="eyebrow">Current progress</p><div className={styles.numbers}><strong>{goal.progress.currentDays}</strong><span>/</span><b>{goal.targetDays}</b></div><p>{goal.progress.remainingDays ? `${goal.progress.remainingDays} progress days remain.` : 'Target reached.'}</p></div><div className={styles.progress}><LinearProgress value={goal.progress.currentDays} max={goal.targetDays} label={`${Math.round(goal.progress.percentage)}% complete`} /><dl><div><dt>Connected habits</dt><dd>{goal.habits.length}</dd></div><div><dt>Deadline</dt><dd>{goal.deadline ?? 'No deadline'}</dd></div><div><dt>Today</dt><dd>{goal.todayStatus === 'COMPLETE' ? 'Complete' : 'In progress'}</dd></div></dl></div></section><section className="panel"><p className="eyebrow">Connected habits</p><h2>Everything that shapes this goal.</h2><div className="stack">{goal.habits.map(habit => <Link className="raisedCard" key={habit.id} to={`/app/habits/${habit.id}`}><strong>{habit.name}</strong><span>{habit.type} · {habit.todayStatus.replace('_', ' ')}</span></Link>)}</div></section><section className={styles.actions}><h2>Goal actions.</h2><p>Changing or removing a goal never blocks habit tracking.</p><div className="cluster">{goal.status === 'ACTIVE' && <button className="raisedSecondary" onClick={() => setConfirm('cancel')}>Cancel goal</button>}<button className="plainButton" onClick={() => setConfirm('delete')}>Delete goal</button></div>{confirm && <div className={styles.confirm}><strong>{confirm === 'cancel' ? 'Cancel this finish line?' : 'Delete this goal permanently?'}</strong><div className="cluster"><button className="raisedSecondary" disabled={cancel.isPending || remove.isPending} onClick={() => confirm === 'cancel' ? cancel.mutate() : remove.mutate()}>Confirm</button><button className="plainButton" onClick={() => setConfirm(null)}>Keep goal</button></div></div>}</section></>;
}
